global:
  scrape_interval: 15s
  evaluation_interval: 15s

remote_write:
  - url: "http://localhost:9090/api/v1/write"
    queue_config:
      max_samples_per_send: 1000
      capacity: 10000
      max_shards: 10

scrape_configs:
  - job_name: "k6"
    static_configs:
      - targets: ["host.docker.internal:9090"]
    metrics_path: "/metrics"
    scheme: "http"
    scrape_interval: 5s
    honor_labels: true

  - job_name: "order-service"
    static_configs:
      - targets: ["host.docker.internal:8080"]
    metrics_path: "/actuator/prometheus"
    scheme: "http"
    scrape_interval: 5s
